In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB 435.7 kB/s eta 0:00:29
   ---------------------------------------- 0.0/12.6 MB 435.7 kB/s eta 0:00:29
   ---------------------------------------- 0.0/12.6 MB 435.7 kB/s eta 0:00:29
   ---------------------------------------- 0.0/12.6 MB 435.7 kB/s eta 0:00:29
   ---------------------------------------- 0.0/12.6 MB 435.7 kB/s eta 0:00:29
   ---------------------------------------- 0.0/12.6 MB 435.7 kB/s eta 0:00:29
   ---------------------------------------- 0.0/12.6 MB 435.7 kB/s eta 0:00:29
   ---------------------------------------- 0.0/12.6 MB 435.7 kB/s eta 0:00:29
   ---------------------------------------- 0.0/12.6 MB 435.7 kB/s eta 0:00:29
   ---------------------------------------- 0.0/12.6 MB 435.7 kB/s eta 0:00:29
   ---------------------------------------- 0.0/12.6 MB 435.7 kB/s eta


[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3])

In [5]:
arr_2d=np.array([[1,2,3],[1,2,3]])

In [9]:
array = np.zeros((4,4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
array = np.ones((3,3))
print(array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
array = np.eye((3))
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
array = np.linspace(0,2,5)
print(array)

[0.  0.5 1.  1.5 2. ]


In [25]:
array = np.arange(0,10,2)
print(array)

[0 2 4 6 8]


In [27]:
array=np.random.rand(2,5)
print(array)

[[0.82100228 0.63935493 0.47895419 0.30769667 0.5197537 ]
 [0.16027075 0.05173399 0.29265893 0.01732353 0.50009709]]


In [28]:
array=np.random.randn(2,5)
print(array)

[[-0.12797067  0.91247878 -0.49306918 -1.47222008 -0.2239684 ]
 [ 0.99324282 -0.22217266  0.71195127 -0.5077676   0.62225225]]


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(2, 3)
2
6
int64


In [36]:
a=np.array([2,3,4,5])
b=np.array([6,7,8,9])
print(a+b)
print(a*b)
np.sin(b)

[ 8 10 12 14]
[12 21 32 45]


array([-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [44]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,6],[5,8]])
print(np.dot(a,b))

[[14 22]
 [32 50]]


In [49]:
a=np.array([2,4,6,8])
print(a.sum())
print(a.max())
print(a.min())
print(a.mean())
print(a.std())

20
8
2
5.0
2.23606797749979


In [63]:
a=np.array([1,2,3,4,5])
print(a[0])
print(a[1:4])
print(a[::2])

1
[2 3 4]
[1 3 5]


In [74]:
a=np.array([[1,2,3],
            [4,5,6]])
print(a[0,1])
print(a[:,1])
print(a[1,:2])

2
[2 5]
[4 5]


In [78]:
a=np.array([1,2,3,4,5])
mask=a>3
print(a[mask])

[4 5]


In [88]:
a=np.array([1,2,3,4,5])
a=np.arange(6)
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [92]:
a=np.array([1,2])
b=np.array([4,5])
np.concatenate((a,b))


array([1, 2, 4, 5])

In [91]:
a=np.array([1,2])
b=np.array([4,5])
np.vstack((a,b))

array([[1, 2],
       [4, 5]])

In [93]:
a=np.array([1,2])
b=np.array([4,5])
np.hstack((a,b))

array([1, 2, 4, 5])

In [98]:
a=np.array([1,2,3,4,5]) + 4
print(a)

[5 6 7 8 9]
